### ISSUE TITLE
Add already existing GDrive Library

### ISSUE THREAD

**Issue by elitistphoenix** [modmore/GoogleDriveMediaSource#2]
The [documentation](https://github.com/modmore/GoogleDriveMediaSource/issues) points to [creating a new project](https://github.com/ivanvermeyen/laravel-google-drive-demo/blob/master/README/1-getting-your-dlient-id-and-secret.md#create-a-project)

How would one point this to an already existing Google Drive/root folder? Is it possible?

**Comment by Mark-H** [comment]
Yes, the project you create is just to hold the authentication for the API. You'll authorize it with a user later, and can use any drive/folder that user has access to.

**Comment by elitistphoenix** [comment]
Thanks
